// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjbYrOg5AhxKjeXmVJd_baqgt_7Fc2wY',
    appId: '1:411339876675:web:6df952fdf184d2c89927f6',
    messagingSenderId: '411339876675',
    projectId: 'tyamo-anas',
    authDomain: 'tyamo-anas.firebaseapp.com',
    storageBucket: 'tyamo-anas.appspot.com',
    measurementId: 'G-691RRP6S82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbQKbnM3kRhgIqtfoGuTPWXYiSGGuUzmA',
    appId: '1:411339876675:android:bf16d787aebf9d169927f6',
    messagingSenderId: '411339876675',
    projectId: 'tyamo-anas',
    storageBucket: 'tyamo-anas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rwdbytDl1awM_bmdbR7ypWA2UX9_Svw',
    appId: '1:411339876675:ios:0474768c312b18099927f6',
    messagingSenderId: '411339876675',
    projectId: 'tyamo-anas',
    storageBucket: 'tyamo-anas.appspot.com',
    iosClientId: '411339876675-cf5qm7c5b6bp9d4p0eesk21r7fvpi63m.apps.googleusercontent.com',
    iosBundleId: 'com.example.tyamoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rwdbytDl1awM_bmdbR7ypWA2UX9_Svw',
    appId: '1:411339876675:ios:6a473f28b17fdd589927f6',
    messagingSenderId: '411339876675',
    projectId: 'tyamo-anas',
    storageBucket: 'tyamo-anas.appspot.com',
    iosClientId: '411339876675-2gn30n2eqgcive6eic8idiv70lb0ggmv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tyamoapp.RunnerTests',
  );
}
